import { StyleSheet } from "react-native";
import { isTablet } from "../../constants";

export const styles = StyleSheet.create({
  container: {
    width: "100%",
    height: isTablet ? 800 : 510,
    overflow: "hidden",
    justifyContent: "center",
    alignItems: "center",
  },
  displayContainer: {
    width: "96%",
    marginHorizontal: 10,
    height: isTablet ? 100 : 70,
    backgroundColor: "white",
    borderWidth: 1,
    borderColor: "#d4d4d8",
    borderRadius: 10,
    shadowColor: "#000",
    elevation: 2,
    overflow: "hidden",
    marginVertical: 20,
  },
  displayText: {
    textAlign: "right",
    padding: 10,
    fontSize: isTablet ? 60 : 40,
    fontWeight: "400",
    color: "#000",
  },
  pageContainer: {
    flex: 1,
    rowGap: 10,
    padding: 5,
  },
  inputContainer: {
    width: "98%",
    paddingHorizontal: 10,
  },
  quickDescriptionContainer: {
    gap: 8,
    height: isTablet ? 150 : 100,
  },
  buttonQuickDescription: {
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "#d4d4d8",
    backgroundColor: "#fff",
    alignItems: "center",
    justifyContent: "center",
    padding: 10,
    width: isTablet ? 120 : 80,
    height: isTablet ? 120 : 80,
  },
  deleteButton: {
    position: "absolute",
    top: 0,
    right: 5,
    fontSize: isTablet ? 20 : 14,
    color: "red",
    fontWeight: "bold",
  },
  button: {
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "#d4d4d8",
    backgroundColor: "#fff",
    margin: 1,
    width: "23.5%",
    height: "23.5%",
    alignItems: "center",
    justifyContent: "center",
    shadowColor: "#000",
  },
  buttonContainer: {
    width: isTablet ? 780 : 400,
    height: isTablet ? 600 : 350,
    flexDirection: "row",
    flexWrap: "wrap",
    alignItems: "center",
    justifyContent: "center",
  },
  textButton: {
    fontSize: 34,
    fontWeight: "bold",
    color: "black",
  },
  label: {
    fontSize: isTablet ? 24 : 16,
    marginTop: isTablet ? 10 : 0,
    fontWeight: "bold",
    color: "black",
  },
  input: {
    backgroundColor: "white",
    fontSize: 16,
    height: isTablet ? 60 : 40,
    borderWidth: 1,
    borderRadius: 5,
    padding: 10,
    textTransform: "capitalize",
  },
  fab: {
    position: "absolute",
    alignItems: "center",
    justifyContent: "center",
    width: isTablet ? 70 : 45,
    height: isTablet ? 70 : 45,
    right: isTablet ? 20 : 10,
    bottom: isTablet ? 20 : 10,
  },
  image: {
    width: isTablet ? 80 : 50,
    height: isTablet ? 80 : 50,
    borderRadius: 5,
  },
  textButtonDescription: {    
    fontSize: isTablet ? 20 : 12,
    textTransform: "capitalize",
  },
});
