import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
    container: {
      width: "94%",
      height: "75%",
      overflow: "hidden",
      marginHorizontal: "auto",
    },
    inputContainer: {
      width: "100%",
      paddingHorizontal: 15,
    },
    quickDescriptionContainer: {
      gap: 8,
      height: 100,
    },
    buttonQuickDescription: {
      borderRadius: 10,
      borderWidth: 1,
      borderColor: "#d4d4d8",
      backgroundColor: "#fff",
      alignItems: "center",
      justifyContent: "center",
      padding: 10,
      width: "auto",
      height: 80,
    },
    deleteButton: {
      position: "absolute",
      top: -2,
      right: 5,
      fontSize: 12,
      color: "red",
      fontWeight: "bold",
    },
    button: {
      borderRadius: 10,
      borderWidth: 1,
      borderColor: "#d4d4d8",
      backgroundColor: "#fff",
      margin: 1,
      width: "23%",
      height: "23%",
      alignItems: "center",
      justifyContent: "center",
      shadowColor: "#000",
    },
    buttonContainer: {
      width: "100%",
      flex: 1,
      flexDirection: "row",
      flexWrap: "wrap",
      alignItems: "center",
      justifyContent: "center",
      marginHorizontal: "auto",
    },
    textButton: {
      fontSize: 34,
      fontWeight: "bold",
      color: "black",
    },
    label: {
      fontSize: 16,
      fontWeight: "bold",
      color: "black",
    },
    input: {
      backgroundColor: "white",
      fontSize: 16,
      height: 40,
      width: "100%",
      borderWidth: 1,
      borderRadius: 5,
      padding: 10,
      textTransform: "capitalize",
    },
    fab: {
      position: "absolute",
      alignItems: "center",
      justifyContent: "center",
      width: 45,
      height: 45,
      right: 0,
      bottom: 10,
    },
    image: {
      width: 50,
      height: 50,
      borderRadius: 5,
    },
  });